vim.g.mapleader = ","

require "user.options"
require "user.telescope"
require "user.lsp-setup"
require "user.mason"
require "user.complete"
require "user.plugins"
require "user.colorscheme"
require "user.mappings"
